apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: python-api
spec:
  selector:
    app: python-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000