apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
    labels:             # <-- ADICIONE ESTA LINHA
      app: python-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
